accounts/urls.py
from django.urls import path

# Views
from .views import profile_view


urlpatterns = [
    path("profile/", profile_view, name="profile"),
]

config/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("allauth.urls")),
    path("accounts/", include("accounts.urls")),
    path("", include("pages.urls")),
    path("todos/", include("todo.urls")),
]

pages/urls.py
from django.urls import path

# Views
from .views import index

urlpatterns = [
    path("", index, name="home"),
]

todo/urls.py
from django.urls import path

# Views
from .views import todo_deleteview, todo_listview, todo_createview, todo_updateview

urlpatterns = [
    path("", todo_listview, name="todo_listview"),
    path("add/", todo_createview, name="new_todo"),
    path("<uuid:pk>/delete/", todo_deleteview, name="todo_delete"),
    path("<uuid:pk>/update/", todo_updateview, name="todo_update"),
]

accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.contrib.auth import get_user_model


class CustomUser(AbstractUser):
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)

    def __str__(self):
        return self.email


class Profile(models.Model):
    user = models.OneToOneField(get_user_model(), on_delete=models.CASCADE)
    about = models.TextField(blank=True)

    def __str__(self):
        return self.user.first_name

pages/models.py
from django.db import models

# Create your models here.

todo/models.py
import uuid
from django.db import models
from django.contrib.auth import get_user_model


def get_users_todos(user):
    try:
        return Todo.objects.filter(user=user)
    except:
        return None


class Category(models.Model):
    name = models.CharField(max_length=20)

    class Meta:
        verbose_name_plural = "Categories"

    def __str__(self):
        return self.name


class Todo(models.Model):
    # Priority choices
    PRIORITY_CHOICES = (
        ("bg-danger", "High"),
        ("bg-info", "Normal"),
        ("bg-warning", "Low"),
    )

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    description = models.CharField(max_length=255)
    priority = models.CharField(max_length=200, choices=PRIORITY_CHOICES, null=True)
    completed = models.BooleanField(default=False)
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    category = models.ManyToManyField(Category)
    """
    due_date
    """

    def __str__(self):
        return self.description

accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

# Models
from .models import Profile


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ("first_name", "last_name", "email")

    def save(self, request):
        user = super(CustomUserCreationForm, self).save(request)

        user.username = self.cleaned_data["email"]
        user.save()

        return user


class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = get_user_model()
        fields = ("email",)


class UpdateUserForm(forms.ModelForm):
    class Meta:
        model = get_user_model()
        fields = (
            "first_name",
            "last_name",
            "email",
        )


class UpdateUserProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ("about",)

todo/forms.py
from django import forms

# Models
from .models import Todo


class NewTodoForm(forms.ModelForm):
    class Meta:
        model = Todo
        fields = ("description", "priority", "completed", "category")


class UpdateTodoForm(forms.ModelForm):
    class Meta:
        model = Todo
        fields = ("description", "priority", "completed", "category")

accounts/views.py
from django.contrib.auth import get_user_model
from django.shortcuts import redirect, render, get_object_or_404


# Models
from .models import Profile

# Forms
from .forms import UpdateUserForm, UpdateUserProfileForm


def profile_view(request):

    template_name = "accounts/profile.html"

    if request.method == "POST":
        user_form = UpdateUserForm(
            request.POST, instance=get_object_or_404(get_user_model(), id=request.user.id)
        )
        profile_form = UpdateUserProfileForm(
            request.POST, instance=get_object_or_404(Profile, user=request.user)
        )

        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()

            return redirect("profile")

    else:
        user_form = UpdateUserForm(instance=get_object_or_404(get_user_model(), id=request.user.id))
        profile_form = UpdateUserProfileForm(instance=get_object_or_404(Profile, user=request.user))

    context = {
        "user_form": user_form,
        "profile_form": profile_form,
    }

    return render(request, template_name, context)

pages/views.py
from django.shortcuts import render


def index(request):

    template_name = "index.html"
    context = {}

    return render(request, template_name, context)

todo/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.db.models import Prefetch

# Models
from .models import Todo, get_users_todos, Category

# Forms
from .forms import NewTodoForm, UpdateTodoForm


def todo_listview(request):

    template_name = "todos/listview.html"
    context = {
        "categories": Category.objects.prefetch_related(
            Prefetch("todo_set", queryset=get_users_todos(user=request.user), to_attr="user_todos")
        ),
    }
    return render(request, template_name, context)


def todo_createview(request):

    template_name = "todos/createview.html"

    if request.method == "POST":
        form = NewTodoForm(request.POST)

        if form.is_valid():
            form.instance.user = request.user
            form.save()
            return redirect("todo_listview")

    else:
        form = NewTodoForm()

    context = {
        "form": form,
    }

    return render(request, template_name, context)


def todo_deleteview(request, pk):

    if request.method == "POST":
        Todo.objects.filter(id=pk).delete()

    return redirect("todo_listview")


def todo_updateview(request, pk):

    template_name = "todos/updateview.html"

    if request.method == "POST":
        todo = get_object_or_404(Todo, id=pk)
        form = UpdateTodoForm(request.POST or None, instance=todo)

        if form.is_valid():
            form.save()
            return redirect("todo_listview")

    else:
        form = UpdateTodoForm(instance=get_object_or_404(Todo, id=pk))

    context = {
        "form": form,
    }

    return render(request, template_name, context)

templates/accounts/profile.html
{% extends 'base.html' %}  
{% load static %}

{% block content %}
    <div class="container">

        <h1 class="mt-3 mb-3">My Profile</h1>

        <form class="border p-3" action="" method="post">
            {% csrf_token %}
            {{ user_form.as_p }}
            {{ profile_form.as_p }}
            <button class="btn btn-success" type="submit">Update</button>
        </form>
    </div>
{% endblock content %}

templates/base.html
<!doctype html>
{% load static %}
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    
    <title>Todo application Django</title>
</head>
    <body>
        <header class="p-3 mb-3 border-bottom">
            <div class="container">
               
                <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
                    <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-dark text-decoration-none">
                        <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap"><use xlink:href="#bootstrap"/></svg>
                    </a>
            
                    <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
                        <li><a href="#" class="nav-link px-2 link-secondary">Overview</a></li>
                        <li><a href="#" class="nav-link px-2 link-dark">Inventory</a></li>
                        <li><a href="#" class="nav-link px-2 link-dark">Customers</a></li>
                        <li><a href="#" class="nav-link px-2 link-dark">Products</a></li>
                    </ul>
                    
                    {% if user.is_authenticated %}
                        <a href="{% url 'todo_listview' %}" class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-5 text-muted text-decoration-none">
                            My Todos
                        </a>
                    {% endif %}
                    

                    {% if user.is_authenticated %}
                        <div class="dropdown text-end">
                            <a href="#" class="d-block link-dark text-decoration-none dropdown-toggle" id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="false">
                                <img src="https://github.com/mdo.png" alt="mdo" width="32" height="32" class="rounded-circle">
                            </a>
                            <ul class="dropdown-menu text-small" aria-labelledby="dropdownUser1">
                                <li><a class="dropdown-item" href="#">{{ user.first_name }}  {{ user.last_name }}</a></li>
                                <li><hr class="dropdown-divider"></li>
                                <li><a class="dropdown-item" href="#">New project...</a></li>
                                <li><a class="dropdown-item" href="#">Settings</a></li>
                                <li><a class="dropdown-item" href="{% url 'profile' %}">Profile</a></li>
                                <li><hr class="dropdown-divider"></li>
                                <li><a class="dropdown-item" href="{% url 'account_logout' %}">Sign out</a></li>
                            </ul>
                        </div>
                    {% else %}
                        <div class="text-end">
                            <a href="{% url 'account_login' %}" class="btn btn-outline-dark me-2">Login</a>
                            <a href="{% url 'account_signup' %}" class="btn btn-warning">Sign-up</a>
                        </div>
                    {% endif %}
            
                </div>
            </div>
        </header>

        {% block content %}
        {% endblock content %}

        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    </body>
</html>

templates/index.html
{% extends 'base.html' %}


{% block content %}
    <div class="container">
        <h1>This is the Homepage</h1>
    </div>
{% endblock content %}

templates/todos/createview.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
<div class="container">
    <div class="row align-items-center py-3 mb-3">
        <div class="col">
            <h2 class="m-0">Create a new Todo</h2>
        </div>
        <div class="col d-flex align-self-center">
            <a class="ms-auto btn btn-info" href="{% url 'todo_listview' %}">&#8592; Back to Todos</a>
        </div>
    </div>
    <form class="border p-3" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-success" type="submit">Create</button>
    </form>
</div>
{% endblock content %}

templates/todos/listview.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class="container">
        <div class="row mb-3">
            <div class="col-6">
                <h1 class="d-inline">My Todos</h1>
            </div>
            <div class="col-6 d-flex ms-auto align-self-center ">
                <a class="ms-auto btn btn-success" href="{% url 'new_todo' %}">+ New Todo</a>
            </div>
        </div>

            {% for category in categories %}
                <h2>{{ category.name }} <span class="badge bg-primary rounded-pill">{{ category.user_todos|length }}</span></h2>
                {% for todo in category.user_todos %}
                <div class="border mb-2 p-3">
                    <div class="row">
                        <div class="col">
                            <span class="badge {{ todo.priority }}">{{ todo.get_priority_display }}</span>
                            
                            {% if todo.completed %}
                                <h4 class="text-decoration-line-through">{{ todo.description }}</h4>
                            {% else %}
                                <h4 class="">{{ todo.description }}</h4>
                                
                            {% endif %}
                        
                        </div>
                        <div class="col-auto">
                            <div class="row g-2">
                                {% comment %} Edit Button Start {% endcomment %}
                                <div class="col">
                                    <a class="btn btn-info" href="{% url 'todo_update' todo.pk %}">Edit</a>
                                </div>
                                {% comment %} Edit Button End {% endcomment %}

                                {% comment %} Delete Button Start {% endcomment %}
                                <div class="col">
                                    <!-- Button trigger modal -->
                                    <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#staticBackdrop">
                                        Delete
                                    </button>
                                    
                                    <!-- Modal -->
                                    <div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
                                        <div class="modal-dialog">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <h5 class="modal-title" id="staticBackdropLabel">Delete?</h5>
                                                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                                </div>
                                                <div class="modal-body">
                                                    <p>Are you sure you want to delete "{{ todo.name }}"?</p>
                                                    
                                                </div>
                                                <div class="modal-footer">
                                                    <span class="form-text me-auto">This action cannot be undone</span>
                                                    <form action="{% url 'todo_delete' todo.pk  %}" method="post">
                                                        {% csrf_token %}
                                                        <button class="btn btn-danger" type="submit">Yes</button>
                                                    </form>
                                                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                {% comment %} Delete Button End {% endcomment %}
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
            {% endfor %}
    </div>
{% endblock content %}

templates/todos/updateview.html
{% extends 'base.html' %}   
{% load static %}

{% block content %}
    <div class="container">
        <h1>Update Todo</h1>

        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button class="btn btn-success" type="submit">Update</button>
        </form>
    </div>
{% endblock content %}